// `npm run contracts:build` — compiles contracts and writes:
//   contracts/artifacts/<Name>.json   ABI + creation bytecode (used by the deploy script)
//   src/lib/contracts/abi.ts          typed `as const` ABIs for viem (used by the app)
// Both are committed; the test suite fails if they drift from the sources.
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { compile, ROOT, SETTINGS } from './compile.mjs'

export const PUBLISHED = ['AchilyonLaunchpad', 'LaunchToken', 'UniswapV2Migrator']

export function renderAbiModule(contracts, version) {
  const body = PUBLISHED.map((name) => {
    const id = name[0].toLowerCase() + name.slice(1) + 'Abi'
    return `export const ${id} = ${JSON.stringify(contracts[name].abi, null, 2)} as const\n`
  }).join('\n')
  return `// Generated by \`npm run contracts:build\` (solc ${version}). Do not edit.\n\n${body}`
}

export function renderArtifact(name, c, version) {
  return JSON.stringify({ contractName: name, sourceName: c.source, compiler: version, settings: SETTINGS, abi: c.abi, bytecode: c.bytecode, deployedSize: c.deployedSize }, null, 2) + '\n'
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { version, contracts } = compile()
  const dir = join(ROOT, 'contracts', 'artifacts')
  mkdirSync(dir, { recursive: true })
  for (const name of PUBLISHED) {
    const c = contracts[name]
    if (c.deployedSize > 24_576) throw new Error(`${name} exceeds the EIP-170 size limit (${c.deployedSize} bytes)`)
    writeFileSync(join(dir, `${name}.json`), renderArtifact(name, c, version))
    console.log(`✓ ${name}  ${c.deployedSize} bytes`)
  }
  mkdirSync(join(ROOT, 'src', 'lib', 'contracts'), { recursive: true })
  writeFileSync(join(ROOT, 'src', 'lib', 'contracts', 'abi.ts'), renderAbiModule(contracts, version))
  console.log('✓ src/lib/contracts/abi.ts')
}
